"""Build _data/publications.yml: a person -> publications index.

papers.bib tags each paper with `tpcb_author`, the TPCB student(s) the program
credited it to, in "Last, First" form. Two lookups fall out of that:

  student page  -> exact name match against tpcb_author
  faculty page  -> the union over that faculty's students and alumni

The faculty case is INDIRECT and must be labelled honestly on the page: it is
"papers co-authored by this lab's TPCB students", not the faculty member's
bibliography, which is far larger. Matching faculty by surname against the
`author` field was rejected — "Chen, J." collides across Jue Chen, Shuibing
Chen and unrelated authors, and getting a real person's publication record
wrong is worse than showing a narrower, accurate list.
"""
import re, glob, os, sys, unicodedata, collections

ROOT = '/Users/aakash/tpcb-website'
OUT = f'{ROOT}/_data/publications.yml'


def norm(s):
    s = unicodedata.normalize('NFKD', s or '')
    s = ''.join(c for c in s if not unicodedata.combining(c))
    return ' '.join(s.lower().replace('.', '').replace('-', ' ').split())


def flip(name):
    """'Baca, Christian' -> 'christian baca'"""
    if ',' in name:
        last, first = name.split(',', 1)
        return norm(first + ' ' + last)
    return norm(name)


def parse_bib():
    src = open(f'{ROOT}/_bibliography/papers.bib', encoding='utf-8').read()
    entries = re.findall(r'(?ms)^@\w+\{.*?\n\}\n', src)
    out = []
    for e in entries:
        def f(name):
            m = re.search(r'(?m)^\s*' + name + r'\s*=\s*\{(.*?)\}\s*,?\s*$', e, re.S)
            return re.sub(r'\s+', ' ', m.group(1)).strip() if m else None
        key = re.match(r'@\w+\{([^,]+)', e).group(1)
        out.append({
            'key': key,
            'title': f('title'),
            'journal': f('journal') or f('booktitle'),
            'year': f('year'),
            'doi': f('doi'),
            'pmid': f('pmid'),
            'note': f('note'),
            'students': [s.strip() for s in (f('tpcb_author') or '').split(';') if s.strip()],
        })
    return out


def front_matter(path):
    txt = open(path, encoding='utf-8').read()
    m = re.match(r'^---\n(.*?)\n---', txt, re.S)
    d, key = {}, None
    if m:
        for line in m.group(1).split('\n'):
            kv = re.match(r'^(\w+):\s*"?(.*?)"?\s*$', line)
            item = re.match(r'^\s+-\s*"?(.*?)"?\s*$', line)
            if kv:
                key = kv.group(1)
                d[key] = kv.group(2)
                if kv.group(2) == '':
                    d[key] = []
            elif item and key and isinstance(d.get(key), list):
                d[key].append(item.group(1))
    return d


def yaml_str(s):
    return '"' + (s or '').replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    pubs = parse_bib()

    # person (normalised) -> advisor slugs
    advisors = collections.defaultdict(set)

    for p in glob.glob(f'{ROOT}/_students/*.md'):
        fm = front_matter(p)
        slugs = fm.get('advisor_slugs') or []
        for s in slugs:
            if s:
                advisors[norm(fm.get('name'))].add(s)

    # Alumni advisors. ONE shape now: `advisor_slugs`, a list, on every record
    # that has any resolvable advisor at all.
    #
    # This used to have to try two shapes, and the plural had to be tried FIRST,
    # because a naive /advisor_slug:\s*"/ does not match `advisor_slugs:` — the
    # next character is `s`, not `:`. When only the singular was tried, the four
    # co-mentored alumni contributed nothing and 22 papers went silently missing
    # from six faculty members' by_faculty lists. Collapsing the data to one
    # shape is what retires that whole class of bug; do not reintroduce a
    # singular key.
    al = open(f'{ROOT}/_data/alumni.yml', encoding='utf-8').read()
    for blk in re.split(r'\n(?=- name:)', al):
        n = re.search(r'- name:\s*"(.*?)"', blk)
        if not n:
            continue
        plural = re.search(r'advisor_slugs:\s*\n((?:\s*(?:#[^\n]*|-\s*"[^"]*")\s*\n)+)', blk)
        slugs = re.findall(r'-\s*"([^"]*)"', plural.group(1)) if plural else []
        for s in slugs:
            if s:
                advisors[norm(n.group(1))].add(s)

    by_person = collections.defaultdict(list)   # normalised person -> keys
    by_faculty = collections.defaultdict(list)  # faculty slug -> keys

    for pub in pubs:
        fac_for_pub = set()
        for student in pub['students']:
            person = flip(student)
            by_person[person].append(pub['key'])
            for slug in advisors.get(person, ()):
                fac_for_pub.add(slug)
        for slug in fac_for_pub:
            by_faculty[slug].append(pub['key'])

    def sort_key(k):
        p = index[k]
        return (-(int(p['year']) if (p['year'] or '').isdigit() else 0), p['title'] or '')

    index = {p['key']: p for p in pubs}

    lines = [
        '# GENERATED by tools/build_pub_index.py — do not edit by hand.',
        '#',
        '# entries:  bib key -> citation fields',
        '# by_person: normalised "first last" -> bib keys (exact tpcb_author match)',
        '# by_faculty: faculty slug -> bib keys, reached through that faculty\'s',
        '#   students and alumni. This is papers co-authored by the lab\'s TPCB',
        '#   students, NOT the faculty member\'s full bibliography — label it so.',
        'entries:',
    ]
    for k in sorted(index):
        p = index[k]
        lines.append(f'  {k}:')
        for field in ('title', 'journal', 'year', 'doi', 'pmid', 'note'):
            if p[field]:
                lines.append(f'    {field}: {yaml_str(p[field])}')
        lines.append('    students: [' + ', '.join(yaml_str(s) for s in p['students']) + ']')

    lines.append('by_person:')
    for person in sorted(by_person):
        keys = sorted(set(by_person[person]), key=sort_key)
        lines.append(f'  {yaml_str(person)}: [' + ', '.join(keys) + ']')

    lines.append('by_faculty:')
    for slug in sorted(by_faculty):
        keys = sorted(set(by_faculty[slug]), key=sort_key)
        lines.append(f'  {slug}: [' + ', '.join(keys) + ']')

    open(OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')

    print(f'publications indexed : {len(index)}')
    print(f'people with papers   : {len(by_person)}')
    print(f'faculty with papers  : {len(by_faculty)}')
    counts = sorted(((len(set(v)), k) for k, v in by_faculty.items()), reverse=True)
    print('\ntop faculty by student-authored papers:')
    for n, slug in counts[:5]:
        print(f'   {n:4d}  {slug}')
    print(f'\nwrote {OUT}')


if __name__ == '__main__':
    main()
